### ISSUE TITLE
Game - Items 

### ISSUE THREAD

**Issue by Julifunk** [PSMGGamesSS2015/PSMG_SS_2015_PuLa#20]
Please enter what Item you are currently working on:

Julia - Glasses - done[2015-05.24]

**Comment by Julifunk** [comment]
Bones

**Comment by schmargi** [comment]
Bomb

**Comment by schmargi** [comment]
Matches

**Comment by schmargi** [comment]
Small Vase
Small Vase broken
normal Vase broken in two different ways

**Comment by schmargi** [comment]
TIkiTiki Statue
