### ISSUE TITLE
Design-Gimmicks

### ISSUE THREAD

**Issue by Julifunk** [PSMGGamesSS2015/PSMG_SS_2015_PuLa#21]
Please enter what Gimmick you are currently working on:

**Comment by schmargi** [comment]
Modelling Cockroach

**Comment by Julifunk** [comment]
Modelling Gates

**Comment by schmargi** [comment]
Animate Cockroach
Modelling Cauldron
Modelling and Animate new Switch

**Comment by Julifunk** [comment]
Modelling a bonfire
Still trying to get the texture right

**Comment by Julifunk** [comment]
Modelling Wall Ornaments

**Comment by Julifunk** [comment]
Modelled a Puddle

**Comment by schmargi** [comment]
Modelling Spider

**Comment by schmargi** [comment]
animate spider
