### ISSUE TITLE
Level Design: Critters

### ISSUE THREAD

**Issue by hmSchuller** [PSMGGamesSS2015/PSMG_SS_2015_PuLa#25]
Critters, like Cockroaches or Snakes make the Game look better and more alive.
These are little Creatures that will run around in the temple. Also they will not affect the player or gameplay at all.

Critters will have following movement pattern:
- While not near the player, critters will walk around, turning randomly once close to a wall
- Once they come too close to a player, they will run away in fear
- Once feared critters get a certain distance to the player they will go back to their normal movement pattern

**Comment by hmSchuller** [comment]
Implemented random movement pattern 
[Link to Commit](https://github.com/PSMGGamesSS2015/PSMG_SS_2015_PuLa/commit/3e77bcca44f35d78d71c4a5f772c4d1b61438643)

**Comment by schmargi** [comment]
they are just animated and have just simple movement now
