### ISSUE TITLE
Design for Level 3

### ISSUE THREAD

**Issue by Julifunk** [PSMGGamesSS2015/PSMG_SS_2015_PuLa#34]
Storyline and Modelling of Level 3

**Comment by hmSchuller** [comment]
@mabeck92 detailed documentation on challenges needed

 Mach das jetzt auf deutsch, damit auch alles klar ist.

Pablo muss die Liane raufklettern um zu seiner Challenge zu kommen.
Challenge Puma:
1. Tikistatuen schießen Speere (die sind auch schon bei den Statuen angebracht), danach steht Pablo vor einem Tor. Jetzt muss Ludwig seine Challenge eingeblendet werden.
2. drei sich bewegende Plattformen (von links nach rechts bzw rechts nach links), danach wieder verschlossenes Tor und der Wechsel zu Ludwig.
3. Zwei Steinkugeln die kurz nacheinander auftauchen und auf Pablo zu rollen (er kann dann entweder drüber springen oder vorbei laufen, die Kugeln sind kleiner als in Level 2), die Kugeln verschwinden sobald er die Streichhölzer erreicht hat. Außerdem geht dann das Tor hinter ihm auf damit er wieder in den Hauptraum kann wo Ludwig steht. 

Challenge Ludwig:

5 Steinplatten jeweils mit einer farbigen Kachel in der Mitte. Die Kacheln leuchten abwechselnd, danach geht das Tor auf und 4 Tikimänner kommen in den Raum. Ludwig muss die 4 Tikimänner anspucken und danach die Kacheln der vorgegebenen Reihenfolge anspucken. Dann öffnet sich ein weiteres Tor für Pablo. Nachdem Pablo die zweite Challenge gemeistert hat, passiert das Ganze noch mal nur diesmal eine andere Abfolge der Farben.
