### ISSUE TITLE
Scripting of Level 3

### ISSUE THREAD

**Issue by Julifunk** [PSMGGamesSS2015/PSMG_SS_2015_PuLa#35]

**Comment by hmSchuller** [comment]
d7610f7fde909b5c85c6c794f6b5a3e9635728ba Puma Challenge1 Complete
ff72565fcf22e431c42838d6c4c19bc994421093 Puma Challenge2 Complete
f7e8419244d7c999b5da36a5c83a9ee60b168814 Puma Challenge3 Complete

All Puma Challenges for Level 3 complete

**Comment by hmSchuller** [comment]
Starting Scripting of Lama Challenge

7fb297ead8371e50e10f5abf67b16d15a9f23bb6 Color sequence is now showing properly.

**Comment by hmSchuller** [comment]
f6ae93e747e69789ea0e3babe647ece5d7bb2d1e lama challenges done

left to do: Ending of scene
